on:
  workflow_call:
    outputs:
      dependencies:
        description: 'project dependencies, versions and licenses'
        value: ${{ jobs.build.outputs.dependencies }}
    inputs:
      package_manager:
        required: true
        type: string
        default: npm
      target_branch:
        required: false
        type: string
        default: main
      working_dir:
        required: false
        type: string
        default: './'
      node_version:
        required: false
        type: string
        default: 18
      submodules:
        required: false
        type: string
        description: >
          Whether to checkout submodules: `true` to checkout submodules or `recursive` to
          recursively checkout submodules.
          When the `ssh-key` input is not provided, SSH URLs beginning with `git@github.com:` are
          converted to HTTPS.
        default: 'false'
    secrets:
      ORG_PAT:
        required: false
      NPM_TOKEN:
        required: false
jobs:
  dependency-check-npm:
    if: ${{ inputs.package_manager }} == 'npm'
    runs-on: ubuntu-latest
    outputs:
      dependencies: ${{ steps.dependencies.outputs.DEPENDENCIES }}
    steps:
      - name: git checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: ${{ inputs.submodules == 'true' }}
        if: (inputs.submodules == 'true' || inputs.submodules == 'false')  && github.event_name != 'workflow_dispatch'

      # assumes the submodules is a private repo
      - name: git checkout w/ recursive submodules
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: ${{ inputs.submodules }}
          token: ${{ secrets.ORG_PAT }}
        if: inputs.submodules == 'recursive' && github.event_name != 'workflow_dispatch'

      # Follow the same git checkout process with submodules but specify a branch ref if it is a workflow_dispatch build
      - name: git checkout workflow_dispatch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: ${{ inputs.submodules == 'true' }}
          ref: ${{ inputs.target_branch }}
        if: (inputs.submodules == 'true' || inputs.submodules == 'false') && github.event_name == 'workflow_dispatch'

      # assumes the submodules is a private repo
      - name: git checkout w/ recursive submodules workflow_dispatch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: ${{ inputs.submodules }}
          token: ${{ secrets.ORG_PAT }}
          ref: ${{ inputs.target_branch }}
        if: inputs.submodules == 'recursive' && github.event_name == 'workflow_dispatch'

      - name: install node@${{inputs.node_version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node_version }}

      - name: install npm dependencies
        run: npm install --production
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: install npm license checker tool
        run: npm install -g license-checker-rseidelsohn

      - name: verify license types
        run: license-checker-rseidelsohn --production --unknown --failOn "GPL;AGPL"
        working-directory: ${{ inputs.working_dir }}

      - name: list dependencies for release
        id: dependencies
        run: |
          DEPENDENCIES=$(license-checker-rseidelsohn --direct 0 --production --unknown --json)
          DEPENDENCIES=$(echo $DEPENDENCIES | jq 'with_entries(.value = .value.licenses)')
          echo "DEPENDENCIES<<EOF" >> $GITHUB_OUTPUT
          echo $DEPENDENCIES >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        working-directory: ${{ inputs.working_dir }}

