on:
  workflow_call:
    outputs:
      image:
        description: 'pushed image'
        value: ${{ jobs.build.outputs.image }}
      image_sha:
        description: 'SHA of pushed image'
        value: ${{ jobs.build.outputs.image_sha }}
    inputs:
      namespace:
        required: true
        type: string
      app:
        required: true
        type: string
      language:
        required: false
        type: string
        default: nodejs
      target_branch:
        required: false
        type: string
        default: main
      aws_region:
        required: false
        type: string
        default: us-east-2
      platform:
        required: false
        type: string
        default: linux/amd64
      docker_push:
        required: false
        type: boolean
        description: Push docker image to the configured registry
        default: false
      push_artifacts:
        required: false
        type: boolean
        description: Push artifacts to S3
        default: false
      target_bucket:
        required: false
        type: string
        description: S3 bucket to push binaries
        default: ''
      docker_image_tag:
        required: false
        type: string
        description: Provide a docker image tag to use for the docker push
        default: ''
      docker_build_args:
        required: false
        type: string
        default: ''
      build_with_npm_token:
        required: false
        type: boolean
        default: false
      next_version:
        required: false
        type: string
        default: ''
      working_dir:
        required: false
        type: string
        default: './'
      submodules:
        required: false
        type: string
        description: >
          Whether to checkout submodules: `true` to checkout submodules or `recursive` to
          recursively checkout submodules.
          When the `ssh-key` input is not provided, SSH URLs beginning with `git@github.com:` are
          converted to HTTPS.
        default: 'false'
      run_component_test:
        required: false
        type: boolean
        description: >
          Whether to run component test.  Requires a makefile target of component-test.
          (support for package.json script to be added in future )
        default: false
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      SLACK_WEBHOOK_URL:
        required: false
      ORG_PAT:
        required: false
      NPM_TOKEN:
        required: false
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.push.outputs.IMAGE }}
      image_sha: ${{ steps.push.outputs.SHA }}
    steps:
      - name: git checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: ${{ inputs.submodules == 'true' }}
        if: (inputs.submodules == 'true' || inputs.submodules == 'false')  && github.event_name != 'workflow_dispatch'

      # assumes the submodules is a private repo
      - name: git checkout w/ recursive submodules
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: ${{ inputs.submodules }}
          token: ${{ secrets.ORG_PAT }}
        if: inputs.submodules == 'recursive' && github.event_name != 'workflow_dispatch'

      # Follow the same git checkout process with submodules but specify a branch ref if it is a workflow_dispatch build
      - name: git checkout workflow_dispatch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: ${{ inputs.submodules == 'true' }}
          ref: ${{ inputs.target_branch }}
        if: (inputs.submodules == 'true' || inputs.submodules == 'false') && github.event_name == 'workflow_dispatch'

      # assumes the submodules is a private repo
      - name: git checkout w/ recursive submodules workflow_dispatch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: ${{ inputs.submodules }}
          token: ${{ secrets.ORG_PAT }}
          ref: ${{ inputs.target_branch }}
        if: inputs.submodules == 'recursive' && github.event_name == 'workflow_dispatch'

      - name: nodejs version
        run: |
          PACKAGE_VERSION=$(jq -r .version package.json)
          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV
        if: inputs.language == 'nodejs'
        working-directory: ${{ inputs.working_dir }}

      - name: provided version
        run: |
          echo "PACKAGE_VERSION=${{ inputs.next_version }}" >> $GITHUB_ENV
        if: inputs.next_version != '' && inputs.language != 'nodejs'
        working-directory: ${{ inputs.working_dir }}

      - name: build version
        id: version
        run: |
          BUILD_VERSION="${{ env.PACKAGE_VERSION }}-$(date +"%Y%m%d")-$GITHUB_RUN_NUMBER"
          if [[ "${{ inputs.docker_image_tag }}" != "" ]]; then
            echo "Using the provided docker image tag: ${{ inputs.docker_image_tag }}"
            BUILD_VERSION="${{ inputs.docker_image_tag }}"
          fi
          echo "IMAGE=${{ inputs.namespace }}-${{ inputs.app }}:$BUILD_VERSION" >> $GITHUB_ENV
        if: github.event_name != 'push' || (github.event_name == 'push' && contains(github.ref, inputs.target_branch))
        working-directory: ${{ inputs.working_dir }}

      # assumes all other pushes are for tags
      - name: release version
        run: |
          TAG_VERSION=$(echo -n "${GITHUB_REF##*/}" | sed 's/v//g')
          if [[ "$TAG_VERSION" != "${{ env.PACKAGE_VERSION }}" ]]; then
            echo "Release tag version [$TAG_VERSION] does not match the app's version [${{ env.PACKAGE_VERSION }}]"
            exit 1
          fi
          echo "IMAGE=${{ inputs.namespace }}-${{ inputs.app }}:${{ env.PACKAGE_VERSION }}" >> $GITHUB_ENV
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        working-directory: ${{ inputs.working_dir }}

      - name: aws creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws_region }}

      - name: registry login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        if: inputs.push_artifacts == true && inputs.platform == 'linux/arm64'

      # assumes linting, unit tests, e2e tests, coverage, etc. are handled by building the image
      - name: build
        run: |
          docker build ${{ inputs.docker_build_args }} . -t $IMAGE
        working-directory: ${{ inputs.working_dir }}
        if: inputs.build_with_npm_token == false && inputs.push_artifacts == false

      - name: build and push binaries
        run: |
          version=$(echo -n "$IMAGE" | cut -d ':' -f2)
          SUB_PATH="${{ inputs.namespace }}-${{ inputs.app }}/$version"
          echo "S3_PATH=$SUB_PATH" >> $GITHUB_ENV

          export DOCKER_BUILDKIT=0
          docker build --platform ${{ inputs.platform }} ${{ inputs.docker_build_args }} --build-arg _AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} --build-arg _AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} --build-arg _PATH="${{ inputs.target_bucket }}" --build-arg _VERSION=$version --build-arg PLATFORM="${{ inputs.platform }}" . -t $IMAGE
        working-directory: ${{ inputs.working_dir }}
        if: inputs.push_artifacts == true

      - name: build with secret args
        run: |
          docker build --build-arg NPM_TOKEN=${{ secrets.NPM_TOKEN }} ${{ inputs.docker_build_args }} . -t $IMAGE
        working-directory: ${{ inputs.working_dir }}
        if: inputs.build_with_npm_token == true

      - name: component-test
        run: |
          make component-test
        working-directory: ${{ inputs.working_dir }}/${{ inputs.app }}
        if: inputs.run_component_test == true

      - name: push
        id: push
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker tag $IMAGE $ECR_REGISTRY/$IMAGE
          docker push $ECR_REGISTRY/$IMAGE
          SHA=$(docker images --no-trunc --quiet $IMAGE)
          echo "Pushed $IMAGE with digest $SHA"
          echo "IMAGE=$IMAGE" >> $GITHUB_OUTPUT
          echo "SHA=$SHA" >> $GITHUB_OUTPUT

        if: github.event_name == 'push' || inputs.docker_push == true
        working-directory: ${{ inputs.working_dir }}

      - name: notify failure
        if: failure() && env.SLACK_WEBHOOK_URL != ''
        uses: slackapi/slack-github-action@v1.16.0
        with:
          payload: |
            {
              "blocks": [
                  {   "type": "divider" },
                  {
                      "type": "section",
                      "text": {
                          "type": "mrkdwn",
                          "text": ":red_circle: ${{ github.workflow }} failed\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}>"
                      }
                  }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK



      